### ISSUE TITLE
Table example

### ISSUE THREAD

**Issue by Neon22** [viking-sudo-rm/rtflib#3]
Hard though it may be for you to accept but this is still useful. :)

However I can't work out how to enter a table.
Any chance you'd update with an example ?

I'm using in pyscript (python online in browser) to make a file for exporting to user's local machine with a bit of formatting.
Would appreciate your help :)

**Comment by viking-sudo-rm** [comment]
> Hard though it may be for you to accept but this is still useful. :)

Wow, I completely forgot about this! What a glad from the past, and glad to hear it's useful :)

> Any chance you'd update with an example ?

I can take a look this weekend. Though I haven't touched this in a long time, so my guess is probably as good as yours

**Comment by viking-sudo-rm** [comment]
I started working on a table branch:
https://github.com/viking-sudo-rm/rtflib/tree/table

 It seems like the library is generally buggy and messy (not just tables). I don't think I'll have time to clean it up properly right now but feel free to take a look at what I started and adapt it

Reference about table formatting: https://stackoverflow.com/questions/8349827/using-tables-in-rtf

**Comment by viking-sudo-rm** [comment]
the formatting of table.rtf is almost right but slightly off:

```rtf
{
{
\colortbl;
\red0\green0\blue0;
\red255\green255\blue255;
}
\cf0 hello world
\trowd\cellx1000\cellx2000\intbl hello\cell
\intbl world\cell
\row
\trowd\cellx1000\cellx2000\intbl hallo\cell
\intbl Welt\cell
\row

}
```

**Comment by Neon22** [comment]
Thanks heaps. It may not be worth your effort these days. Appreciate it though. I'll manage. Cheers...

**Comment by viking-sudo-rm** [comment]
Actually, I decided to go back and fix up the library. Tables are working now! I added an example and test case to show how they work.

Some features (like adding borders) aren't supported right now, but it shouldn't be too hard to extend the cleaned-up code to add them
