### ISSUE TITLE
table issues and examples

### ISSUE THREAD

**Issue by Neon22** [viking-sudo-rm/rtflib#6]
Add a PR for a demo where multiple lines are written.

Couple more things to demo/test:

1. If you use color in a table `Line()` then that rfcode is not generated properly. I am not sure why.
2. E.g.
```
rtf.add(Table(
		Row(Line("hello", color=Color(0,255,0)), Line("world")),
		Row(Line("hallo"), Line("Welt")),
	))
```

3. Noticed a couple of extra newline chars in the output (specifically my new multiline test file) which may not be needed but unsure how best to contract/simplify them. (The global var in the test file shows them also)

4. The ends keyword has no examples. It looks like this can be used to specify borders but not sure.

**Comment by Neon22** [comment]
Tried to use format to add say 'bold'. Could not get it to work.
Any ideas ?
E.g. 
```
rtf.add(Line("hello world. A Line of text.\n", format=['bold','underline']))
```

or `format='bold'` or `format={bold=True}` etc...

**Comment by viking-sudo-rm** [comment]
The correct syntax would be:

```python
from rtflib import Format
rtf.add(Line("hello world. A Line of text.\n", format=Format(bold=True)))
```

**Comment by Neon22** [comment]
ok. updated the PR - removed the globals.

**Comment by viking-sudo-rm** [comment]
> The ends keyword has no examples.

`ends` specifies the ending position of each column in the table. If you don't pass any number, I believe it defaults to 1000.

**Comment by Neon22** [comment]
yes - worked it out. Got a demo coming.
Been manually trying to play with borders on Table.
